### ISSUE TITLE
[arch] configure callout icons and colors

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/personal-assistant#38]
## Subject
callout supporting lots of icons and has its color scheme for each other, try to enable this ability in this plugin.

reference link:
- [Bluemoondragon07/obsidian-notation-2](https://github.com/Bluemoondragon07/obsidian-notation-2)

## Tasks
- [ ] callout plugins in market
- [ ] this plugin will do:
    - [ ] feat 1(to be determined)
