### ISSUE TITLE
[Review] fix obsidian plugin community review issue

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/personal-assistant#56]
## Description
Obsidian plugin community has already submitted review comments in PR [#1851](https://github.com/obsidianmd/obsidian-releases/pull/1851), I will fix them.

## Tasks
- [x] [// Perform additional things with the ribbon](https://github.com/edonyzpc/personal-assistant/blob/906b91dc3554c68c1ebfc9c27817e3ecd4296b18/src/plugin.ts#L56-L57)
Remove this.

- [x] [id: 'assistant-memos',](https://github.com/edonyzpc/personal-assistant/blob/906b91dc3554c68c1ebfc9c27817e3ecd4296b18/src/plugin.ts#L83)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

- [x] [hotkeys: [{ modifiers: ["Mod", "Shift"], key: "m" }],](https://github.com/edonyzpc/personal-assistant/blob/906b91dc3554c68c1ebfc9c27817e3ecd4296b18/src/plugin.ts#L85)
While there's no hard rule against it, we recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems.

- [x] [const directoryExists = await adapter.exists(directoryPath);](https://github.com/edonyzpc/personal-assistant/blob/906b91dc3554c68c1ebfc9c27817e3ecd4296b18/src/plugin.ts#L151-L182)
This block of code can be replaced with:
```typescript
if(vault.getAbstractFileByPath(directoryPath) === undefined) {
    vault.createFolder(directoryPath);
}
```
- [x] [const fileExists = await adapter.exists(filePath);](https://github.com/edonyzpc/personal-assistant/blob/906b91dc3554c68c1ebfc9c27817e3ecd4296b18/src/plugin.ts#L198)
It's better to check if this.app.vault.getAbstractFileByPath(filePath) instanceof TFile.
