### ISSUE TITLE
[feat] automatically update plugin with one command

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/personal-assistant#70]
## Description
Update plugins with one command, no clickings in the setting tab.

### Requirement/Scenario
I need to do clicking multiple times in the setting tab when updating plugins which is wasting my time.

### Function
Update plugins that I have installed from Obsidian community with one command.

## Tasks
- [ ] List local plugins
- [ ] Check each local plugin status, including repo validation about release files(main.js, styles.css, manifest.json)
- [ ] Get each local plugin latest release version
- [ ] Check if the plugin needs to upgrade and display the status
- [ ] Trigger the upgrading for all outdated plugins

**Comment by edonyzpc** [comment]
Try this API of Github
```js
const response = await this.request('https://api.github.com/repos/edonyzpc/personal-assistant/releases/latest');
// undefined
JSON.parse(response)
// {url: 'https://api.github.com/repos/edonyzpc/personal-assistant/releases/101453364', assets_url: 'https://api.github.com/repos/edonyzpc/personal-assistant/releases/101453364/assets', upload_url: 'https://uploads.github.com/repos/edonyzpc/personal-assistant/releases/101453364/assets{?name,label}', html_url: 'https://github.com/edonyzpc/personal-assistant/releases/tag/1.1.0', id: 101453364, …}
```
