### ISSUE TITLE
[feat] automatically update theme with one command

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/personal-assistant#71]
## Description
Update theme with one command, no clicking in the setting tab.

### Requirement/Scenario
I need to do clicking multiple times in the setting tab when updating theme which is wasting my time.

### Function
Update theme that I have installed from Obsidian community with one command.

## Tasks
- [x] List local themes
- [x] Check each local theme status, including repo validation about release files(manifest.json, theme.css)
- [x] Get each local theme latest release version
- [x] Check if the theme needs to upgrade and display the status
- [x] Trigger the upgrading for all outdated themes
